Repository green-labs/gosura, pull requests merged in 2022-06, with the labels that each got.

#9 gosura init
  .gitignore
  README.md
  src/deps.edn
  src/gosura/auth.clj
  src/gosura/builders/resolver.clj
  src/gosura/core.clj
  src/gosura/helpers/db.clj
  src/gosura/helpers/error.clj
  src/gosura/helpers/node.clj
  src/gosura/helpers/relay.clj
  src/gosura/helpers/resolver.clj
  src/gosura/helpers/response.clj
  src/gosura/helpers/superlifter.clj
  src/gosura/schema.clj
  src/gosura/util.clj
Labels: release:minor

#10 Relocate deps.edn
  deps.edn
Labels: release:patch

#12 bad require ns
  src/gosura/helpers/resolver.clj
Labels: bug, release:patch

#13 fix bad require
  src/gosura/core.clj
Labels: bug, release:patch

#16 Create LICENSE
  LICENSE
Labels: documentation

#26 better conditional check for server-error fn
  src/gosura/helpers/response.clj
Labels: bug

#24 Add country language filter
  src/gosura/auth.clj
  src/gosura/core.clj
  src/gosura/helpers/resolver.clj
  src/gosura/schema.clj
  src/gosura/util.clj
  test/gosura/auth_test.clj
  test/resources/gosura/sample_resolver_configs.edn
Labels: enhancement, release:patch

#15 Update readme
  README.md
Labels: documentation

#32 Add resolve-update-multi
  src/gosura/core.clj
  src/gosura/helpers/resolver.clj
  src/gosura/schema.clj
Labels: enhancement
